language: php

php:
  - 7.1

before_install:
  - composer require php-coveralls/php-coveralls

before_script:
  - composer self-update
  - composer install --prefer-source --dev

script: vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
 - php vendor/bin/php-coveralls -v